### ISSUE TITLE
auto point click does not work

### ISSUE THREAD

**Issue by tryfresh** [MarkM-dev/Twitch-Previews#14]
so we use anothere extension

**Comment by MarkM-dev** [comment]
works here.. it runs in 15 seconds intervals (best for performance) to check if there is a bonus points button available to be claimed.
what browser are you using and what version of the extension are you using?

also it's possible that your extension got updated in the background (while twitch was opened) since there was an update yesterday and if you refresh the page to reload the newly updated extension on it, it should work.

also, disable other bonus claimer extensions you have and when a bonus points button appears, see if there's an error in the developer console (F12) related to the extension or has a reference to a file called "core.js". (it should show an error every 15 seconds in the console if it encounters a problem claiming the bonus points).
