### ISSUE TITLE
Chatting is disabled for channel owner/mods because the Twitch Chat window is obscured by another element (chat embeds).

### ISSUE THREAD

**Issue by kochetov2000** [MarkM-dev/Twitch-Previews#27]
I am a moderator on a single channel, and when I turn on multistream, I cannot write to the twitch chat due to the message indicated in the title. I have been looking at the code for a very long time and still do not understand why this is happening. On other channels (probably due to the fact that I'm not a moderator) I have no problems sending messages in the twitch chat

**Comment by MarkM-dev** [comment]
huh.. very strange. ill look into it for the next versions.

**Comment by MarkM-dev** [comment]
it seems like this is a twitch thing, there's nothing i can do.

**Comment by Renari** [comment]
I ran into this issue today, I noticed that if you change the iframe source to `https://www.twitch.tv/popout/<channel>/chat?popout=` instead of `https://www.twitch.tv/embed/<channel>/chat?darkpopout&parent=twitch.tv` the chat works, but shortly after changing it, the iframe will be reset and simply read `null`.
