### ISSUE TITLE
FB Sidebar Bug, Inputs random FB streamer, No Prompt To Approve FB

### ISSUE THREAD

**Issue by ScottSterlingMML** [MarkM-dev/Twitch-Previews#36]
Not getting a prompted when enabling the FB sidebar. I'm logged out of FB and have cleared the cookies or sign in, through Chrome.
Also I have blockers that would have prompted me if something was trying to pop up and nothing prompted me about anything. Really was excited to be able to watch FB streamers again.
![chrome_9lP9DpwNCg](https://user-images.githubusercontent.com/68624015/153059327-e27f025b-ae50-4c70-8bf5-5462c8fe4b5f.png)
![chrome_tlKwsIqzah](https://user-images.githubusercontent.com/68624015/153059360-dc212075-b887-44d0-a848-c474893c9757.png)
![chrome_DBrk7z55b5](https://user-images.githubusercontent.com/68624015/153059371-6613fe1a-2a0d-403c-a217-44c97f16a5b8.png)

![chrome_EUX5ZumQpl](https://user-images.githubusercontent.com/68624015/153059367-5d37bdf5-cc75-447c-afcd-7e4981b323d7.png)

**Comment by MarkM-dev** [comment]
hi,
1. remove the commas from the names you entered. (it should of separated automatically but this will be fixed in the next version).
2. you probably approved the extension to fetch from facebook (you have items on the fb sidebar) so no need for a prompt anymore.

should be fixed once you remove the commas at the end of the names and click save.

**Comment by ScottSterlingMML** [comment]
That seems to fix it, Thanks.
