### ISSUE TITLE
FB gaming channels on sidebar

### ISSUE THREAD

**Issue by dabssss** [MarkM-dev/Twitch-Previews#48]
Around 3:30 pm EST every day I'm not able to see Facebook streamers on my sidebar. It says "error-click to see details" for every FB stream I've added. If I click on it, it brings up a stream or a VOD of some streamer named "NULL". No clue who null is nor have I ever followed or watched him
![Screenshot 2022-03-07 161837](https://user-images.githubusercontent.com/101146475/157119525-64b5a1a5-ed54-4c5b-9e07-759ad51eb4da.png)

**Comment by MarkM-dev** [comment]
i assume you are not logged into facebook. what you are seeing is because of facebook's policy where if you are not logged in, it will ask you to log into facebook (which translates to the errors you are seeing) after a number of fetches (not sure how their spam filter works yet).
when you click the items, it should bring you here:  https://github.com/MarkM-dev/Twitch-Previews/issues/41
i've also noticed that sometimes it just fixes by itself after a while without doing the above.

as development continues i'll try to make this feature more robust, but for now.. it's what we got :)
