### ISSUE TITLE
Please fix this error quickly

### ISSUE THREAD

**Issue by clickrail** [MarkM-dev/Twitch-Previews#69]
First of all, I always keep the sidebar closed. Originally, when hovering a mouse over a streamer on the sidebar, the sidebar automatically expands and displays all the live streamers, but at some point, even if I hover a mouse over a streamer on the sidebar, it just shows a preview of the live streamers, and the sidebar does not expand automatically, and there is an error that shows only a part of the live streamers.  
Because of this, I have to press the sidebar extension button and close it again. Please fix it quickly.

**Comment by MarkM-dev** [comment]
twitch changed the way the sidebar behaves for some users.
you can change it to what is was using ffz experimental features (go to their settings to the experimental section and search for "hover").
the following image is from twitch previews settings menu:
![image](https://user-images.githubusercontent.com/38380938/174478270-c51c6ddf-bc1d-4d5d-9e6c-3de8a990a5ba.png)

populating your favorites while the sidebar is collapsed will result in bad user experience since you need to expand it, wait for it to populate and then collapse it back again. i will try to think of a solution because twitch also started refreshing the page.
