### ISSUE TITLE
Audio playing when I mouse over a stream and then move away

### ISSUE THREAD

**Issue by asherbasher** [MarkM-dev/Twitch-Previews#71]
I don't have exact steps to reproduce the issue but I've noticed when I'm watching a stream and accidentally hover over a followed channel for a brief second and then move away, it will start playing the audio even though the preview is not there. Caused quite some confusion the first few times because I had no idea where the audio was coming from.

Expected behaviour is:
- Hover mouse over followed channel
- Preview appears and audio plays
- Move mouse away from followed channel
- Preview disappears and audio stops playing

Currently I'm getting:
- Accidentally hover mouse over followed channel (without realising sometimes)
- Move mouse away from channel
- Audio is playing until I trigger a new preview

Doesn't seem to happen every time, might be only when moving fast over the list of channels or something, but I can reproduce it some of the time when actively trying to trigger it.

**Comment by MarkM-dev** [comment]
i've received a similar report from someone, the culprit turned out to be a different extension called "Hover Zoom +".
try disabling all other extensions you have except twitch previews then refresh twitch and check if it keeps happening.

Twitch Previews will always start the previews muted by definition (it's an attribute on the embedded iframe).

**Comment by asherbasher** [comment]
Great! Didn't expect a fix since it probably wouldn't affect 99% of users. Glad you are looking into it.

**Comment by MarkM-dev** [comment]
Fixed in 4.1, thanks for letting me know about the issue.
