### ISSUE TITLE
[Feature Request] always theater mode | disable all animations of Twitch Preview

### ISSUE THREAD

**Issue by JadeMin** [MarkM-dev/Twitch-Previews#78]
title says it all

**Comment by MarkM-dev** [comment]
i think ffz has always theater or maybe bttv. it's not something that i'm interested in because of several reasons.
i try to make the animations as smooth and as less time wasting as possible while other things are also happening in the background that we have to wait for, animations help smooth transitions and scenarios so everything feels polished and not clunky.

**Comment by JadeMin** [comment]
i know the animations help smooth transitions and scenarios
but i've some troubles because my readability issues and low-end pc.
so i mean if there is the disable animations option it'll be very helpful for some users have troubles about this.
